package com.kerem.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.UuidGenerator;

import java.util.Date;
import java.util.List;

@Entity
@Table(name = "RESERVATION")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Reservation {

    @Id
    @UuidGenerator
    private String reservationNumber;       // Must be autogenerated 8 digit string
    private Date creationDate;
    private Date pickUpDateAndTime;
    private Date dropOffDateAndTime;

    @Column(length = 10, nullable = false)
    @Enumerated(EnumType.STRING)
    private Status status;
    public enum Status {
        ACTIVE,
        CANCELLED,
        COMPLETED
    }

    @OneToOne
    private Location pickUpLocation;
    @OneToOne
    private Location dropOffLocation;

    @ManyToOne
    @JoinColumn(name = "customer_ssn")
    private Customer customer;

    @OneToMany
    @JoinTable(name = "REF_RESERVATION_EXTRAS",
    joinColumns = @JoinColumn(name = "reservation_number"),
    inverseJoinColumns = @JoinColumn(name = "extra_service_id"))
    private List<ExtraService> extras;
}
