package com.kerem.carrental.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.UuidGenerator;

import java.util.Date;
import java.util.List;

@Entity
@Table(name = "RESERVATION")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Reservation {

    @Id
    @UuidGenerator
    private String reservationNumber;               // Must be autogenerated 8 digit string
    private Date creationDate;
    private Date pickUpDateAndTime;
    private Date dropOffDateAndTime;

    @Column(length = 10, nullable = false)
    @Enumerated(EnumType.STRING)
    private Status status;
    public enum Status {
        ACTIVE,
        CANCELLED,
        COMPLETED
    }

    @OneToOne
    private Location pickUpLocation;
    @OneToOne
    private Location dropOffLocation;

    @OneToMany
    private List<ExtraService> extras;
}
