package com.kerem.carrental.model;

import java.sql.Date;
import java.util.List;

public class Reservation {

    private String reservationNumber; // Must be autogenerated 8 digit string
    private Date creationDate;
    private Date pickUpDateAndTime;
    private Date dropOffDateAndTime;
    private String status; // ACTIVE, COMPLETED, CANCELLED

    // Relationships to other domain objects:
    private Customer member;
    private Car car;
    private Location pickUpLocation;
    private Location dropOffLocation;
    private List<ExtraServiceAndEquipment> extras;

}
